### PR TITLE
Add local storage in order to retrieve data if available

### PR DESCRIPTION
**Pull request by Alejandroq12**
## Dear Reviewer,

I have implemented the required interactions as per the project requirements. Please find below a summary of the changes made to the codebase to meet the project requirements.

-- I created a JavaScript single object formData that contains all the data from the entire form. 😎

-- On page load, I retrieved any saved data from the local storage using localStorage.getItem('form-data'). If any data is available, I parsed it using JSON.parse and assigned it to the formData object. 👌

-- I added event listeners to the input fields to listen for any changes in their values using the input event. 👌

-- Whenever a change event is triggered, I updated the corresponding property of the formData object with the new value and saved the entire object to local storage using localStorage.setItem('form-data', JSON.stringify(formData)).

-- Finally, on page load, I pre-filled the input fields with the saved data (if any) by setting their value properties to the corresponding properties of the formData object.

-- All linters tests are passed

-- Correct GitHub Workflow

-- My coding partner also pushed changes

-- Descriptive Pull Request

Please review the code and let me know if any further changes are required. 🚨

Thank you.
GreatDayGIF

image

Requirements:
https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/10_localstorage.md

### CODE REVIEW

**Comment by huseyinbiyik** [comment]
Hi team,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

Alt Text

## Invalid Code Review Request

You have submitted a project, that has templated text on README. Kindly remove the text below since they are aiming to inform you not the visitor 👍 
Screenshot 2023-03-09 at 8 42 33 PM


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Alejandroq12** [comment]
Thank you very much for your feedback!
I fixed it
Have a good day.

**Review by m05e5 — APPROVED** [review]
**Hi @Alejandroq12 
You did great. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
CleverScornfulBuffalo-size_restricted

## Highlights

✔️ Clean and well-organized code
✔️ No Linters error
✔️ Nice UI

## Optional suggestions



_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**m05e5**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._**

**Comment by Alejandroq12** [comment]
Thank you very much for your time. Have a very good day.

**Pull request merged**
